//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using GMS.Framework.Contract;
using System.Collections.Generic;
using GMS.Framework.Utility;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Web;

namespace GMS.Audit.Contract
{
    using System;
    using System.Collections.Generic;
    
    [Table("Scrap")]
    public partial class Scrap : ModelBase
    {
        public string Code { get; set; }
        public int SeqID { get; set; }
        public Nullable<double> Servicelife { get; set; }
        public string Reason { get; set; }
        public string AuditState { get; set; }
        public Nullable<int> ApplicantID { get; set; }
        public Nullable<int> Auditor1 { get; set; }
        public Nullable<int> Auditor2 { get; set; }
        public int ID { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<System.DateTime> ScrapDate { get; set; }
    }
}
