//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMS.ToolManage.Contract
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GMSToolManageEntities : DbContext
    {
        public GMSToolManageEntities()
            : base("name=GMSToolManageEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<attachments> attachments { get; set; }
        public DbSet<authorization> authorization { get; set; }
        public DbSet<emails> emails { get; set; }
        public DbSet<employees> employees { get; set; }
        public DbSet<location> location { get; set; }
        public DbSet<maintenance_record> maintenance_record { get; set; }
        public DbSet<manager> manager { get; set; }
        public DbSet<@operator> @operator { get; set; }
        public DbSet<operator1> operator1 { get; set; }
        public DbSet<operator2> operator2 { get; set; }
        public DbSet<production_line> production_line { get; set; }
        public DbSet<send_emails> send_emails { get; set; }
        public DbSet<supervisor> supervisor { get; set; }
        public DbSet<system_email_account> system_email_account { get; set; }
        public DbSet<tongs_definition> tongs_definition { get; set; }
        public DbSet<upkeep_check> upkeep_check { get; set; }
        public DbSet<users> users { get; set; }
        public DbSet<OutTable> OutTable { get; set; }
    }
}
