//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMS.ToolManage.Contract
{
    using System;
    using System.Collections.Generic;
    
    public partial class maintenance_record
    {
        public string Code { get; set; }
        public int SeqID { get; set; }
        public string ErrDescription { get; set; }
        public string ErrPhoto { get; set; }
        public Nullable<int> ApplicantID { get; set; }
        public Nullable<int> Operator2ID { get; set; }
        public string MaintainState { get; set; }
        public Nullable<System.DateTime> MaintainDate { get; set; }
        public Nullable<int> SupervisorID { get; set; }
    }
}
