//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMS.ToolManage.Contract
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchase_warehousing_application
    {
        public string Code { get; set; }
        public int SeqID { get; set; }
        public string buyoff { get; set; }
        public Nullable<System.DateTime> jbuyoff { get; set; }
        public string Owner { get; set; }
        public string Family { get; set; }
        public string Model { get; set; }
        public string AuditState { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
        public Nullable<int> Operator2 { get; set; }
        public Nullable<int> Supervisor { get; set; }
        public Nullable<int> Manager { get; set; }
        public string Location { get; set; }
        public Nullable<int> bin { get; set; }
    }
}
