//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMS.ToolManage.Contract
{
    using System;
    using System.Collections.Generic;
    
    public partial class send_emails
    {
        public int ESRID { get; set; }
        public System.DateTime ReceiveTime { get; set; }
        public string IsReaded { get; set; }
        public Nullable<int> EmailID { get; set; }
        public Nullable<int> sender { get; set; }
        public Nullable<int> recipient { get; set; }
    }
}
