//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMS.ToolManage.Contract
{
    using System;
    using System.Collections.Generic;
    
    public partial class tongs_entity
    {
        public string Code { get; set; }
        public int SeqID { get; set; }
        public string Model { get; set; }
        public string PartNo { get; set; }
        public string BillNo { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
        public string Location { get; set; }
        public Nullable<int> Bin { get; set; }
        public string State { get; set; }
        public string Photo { get; set; }
        public Nullable<int> UsedCount { get; set; }
        public string ErrProbability { get; set; }
        public int ID { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
