//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMS.ToolManage.Contract
{
    using System;
    using System.Collections.Generic;
    
    public partial class tongs_scrapping
    {
        public string Code { get; set; }
        public int SeqID { get; set; }
        public Nullable<double> Servicelife { get; set; }
        public string Reason { get; set; }
        public string AuditState { get; set; }
        public Nullable<int> ApplicantID { get; set; }
        public Nullable<int> Auditor1 { get; set; }
        public Nullable<int> Auditor2 { get; set; }
    }
}
