//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using GMS.Framework.Contract;
using System.Collections.Generic;
using GMS.Framework.Utility;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Web;

namespace GMS.ToolManage.Contract
{
    using System;
    using System.Collections.Generic;
    
    [Table("tongs_definition")]
    public partial class tongs_definition : ModelBase
    {
        public string Code { get; set; }
        public Nullable<int> WorkcellID { get; set; }
        public string Workcell { get; set; }
        public Nullable<int> FamilyID { get; set; }
        public string Family { get; set; }
        public string Name { get; set; }
        public string Model { get; set; }
        public string PartNo { get; set; }
        public string Type { get; set; }
        public string UsedFor { get; set; }
        public Nullable<int> UPL { get; set; }
        public Nullable<int> Owner { get; set; }
        public string OwnerName { get; set; }
        public string Remark { get; set; }
        public string PMPeriod { get; set; }
        public string PMType { get; set; }
        public Nullable<System.DateTime> RecOn { get; set; }
        public Nullable<int> RecBy { get; set; }
        public string RecByName { get; set; }
        public Nullable<System.DateTime> EditOn { get; set; }
        public Nullable<int> EditBy { get; set; }
        public string EditByName { get; set; }
    }
}
