//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using GMS.Framework.Contract;
using System.Collections.Generic;
using GMS.Framework.Utility;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Web;

namespace GMS.ToolManage.Contract
{
    using System;
    using System.Collections.Generic;
    
    [Table("users")]
    public partial class users : ModelBase
    {
        public int username { get; set; }
        public string Password { get; set; }
        public Nullable<int> EmpID { get; set; }
        public int Level { get; set; }
    }
}
