//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using GMS.Framework.Contract;
using System.Collections.Generic;
using GMS.Framework.Utility;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Web;

namespace GMS.ToolManage.Contract
{
    [Table("tongs_entity")]
    public partial class tongs_entity : ModelBase
    {
        public string Code { get; set; }
        public int SeqID { get; set; }
        public string Model { get; set; }
        public string PartNo { get; set; }
        public string BillNo { get; set; }
        public DateTime RegDate { get; set; }
        public string Location { get; set; }
        public int Bin { get; set; }
        public string State { get; set; }
        public string Photo { get; set; }
        public int UsedCount { get; set; }
        public string ErrProbability { get; set; }
        public int Workcell { get; set; }
        public int ID { get; set; }
        public DateTime CreateTime { get; set; }
        [NotMapped]
        public HttpPostedFileBase ImagePath { get; set; }
    }
}
